### ISSUE TITLE
WIND Toolkit download not pulling correct measurement heights

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1425] opened 2023-08-03 15:04 UTC
### Describe the bug

The wind resource download tool is not pulling the measurement heights I selected. 

### To Reproduce

1. Go to WIND Toolkit download interface
2. Enter a location and select measurement heights of 100, 120, 140, and 160 m
3. Hit "ok"
4. Open the file that was downloaded and check the heights available

### Screenshots

![image](https://github.com/NREL/SAM/assets/45701090/50cb4b03-02c1-4885-a0dc-e0a3fcecb037)

![image](https://github.com/NREL/SAM/assets/45701090/5521ffc6-f4c4-4361-91f2-409b6db3abce)

<img width="843" alt="image" src="https://github.com/NREL/SAM/assets/45701090/d895dd66-6d0f-436b-b07a-dff1e283480e">

### Operating System and Version

 - OS: Windows 11
 - Version: SAM 2022.11.21 r3

**Comment by cpaulgilman** [comment] 2023-08-10 17:08
This is caused by a bug in the code that generates the URL for the WIND Toolkit API call -- the measurement heights are hard-coded at 100 m and 120 m: https://github.com/NREL/SAM/blob/11cfdf436af45b96a510f965230d1dbc7bbfa925/src/invoke.cpp#L2939

This is fixed in https://github.com/NREL/SAM/blob/f8654c78b95955bbbf4ba51f85146d943f5f1789/src/invoke.cpp#L2940.

There is a separate issue with the WIND Toolkit API returning N/A for wind speed data at 120 m that needs to be resolved by the API team.

**Comment by williamhobbs** [comment] 2023-08-10 17:19
Thanks!

**Closed** 2023-10-04 15:10 UTC
Labels: bug
