### ISSUE TITLE
PVWatts No financial Advanced Inputs callback error

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#1310] opened 2023-01-04 08:32 UTC
With 2022.11.21 release:
1. Create PVWatts / No Financial Model case
2. System Design->Advanced Inputs->Edit shading...
3. Enable one or more shading options
4. Simulate
5. Click on System Design page

Receive callback error
![image](https://user-images.githubusercontent.com/6498311/210514720-de1c9433-1da6-4405-99a3-f6b417ab61be.png)

**Comment by cpaulgilman** [comment] 2023-01-04 19:57
This is a duplicate of https://github.com/NREL/SAM/issues/1305

**Closed by cpaulgilman** 2023-01-04 19:57 UTC
Labels: bug
