### ISSUE TITLE
Defaults have been reset

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/SAM#419] opened 2020-11-02 19:04 UTC
A somewhat recent commit has reset a few of our defaults, and since this has happened before, is there a problem with our methods or tools for doing this kind of work? Can someone please revert the errors in this commit? For an example, see the file:  deploy/runtime/defaults/Physical Trough_Single Owner.txt

https://github.com/NREL/SAM/commit/55d098c81843b8d72fed6e746dc629ec303de15a#diff-433f9b4ce708065fed50e34c62c2a939665c216a5bd2a3fd7edcf7f871a94d35

**Comment by Matthew-Boyd** [comment] 2020-11-03 15:02
This commit should be reverted after this bug has been addressed:

https://github.com/NREL/ssc/commit/e06fd832e85b29563725615d0b96c58e43c64f2e

**Comment by cpaulgilman** [comment] 2020-11-03 16:40
@Matthew-Boyd Do defaults for any variables other than `tes_lengths` need to be fixed?

It looks like that commit changed the default of `tes_lengths` for all Physical Trough configurations from

`tes_lengths = [ [ 0, 90, 100, 120, 0, 30, 90, 80, 80, 120, 80 ] ]`  to

`tes_lengths = [ [ 0, 90, 100, 120, 0, 0, 0, 0, 80, 120, 80 ] ]`.

I'm not sure if that has something to do with the way the defaults manager works with variables like `tes_lengths` that are in the user interface but do not have a widget associated with them.

For this fix, I will change the default values back and make sure that the values in the defaults .txt files match the values in the variable properties:

![image](https://user-images.githubusercontent.com/27711933/98013738-9a4aae80-1daf-11eb-8f50-3441b8647db9.png)

Perhaps another reason to avoid using Shift-F10 to set defaults.

**Comment by Matthew-Boyd** [comment] 2020-11-03 17:20
@cpaulgilman I don't know if these were the only defaults that were affected, but none of the CSP defaults should have been changed with this commit.

I remember having to fix this once before, and I did it via the Defaults manager (I haven't used Shift-F10 for at least a year now). Maybe someone else hit Shift-F10, which then updated them using the 'Default Value's you're pointing to there? So partly our fault for having out-of-date values in the User Interface?

**Comment by cpaulgilman** [comment] 2020-11-03 18:22
That is my working theory, but my initial tests do not support it: Shift-F10 did not overwrite the defaults .txt file with values from the UI variable properties.

**Comment by tyneises** [comment] 2020-11-03 21:07
Reverted Physical Trough compute module here: https://github.com/NREL/ssc/commit/ac1f85985d15cd717bfb5c04ca89644eadabf01e

**Comment by tyneises** [comment] 2020-11-03 21:09
@Matthew-Boyd Do we need to pass hard-coded, hidden values from the UI to the compute module? Can you make the SSC INPUT optional, check in the compute module whether it's assigned and properly formatted, and then set to defaults if necessary?

**Comment by tyneises** [comment] 2021-02-02 21:52
There's a few unresolved problems here.
1) SAM seems to be passing to LK/SSC the value for "tes_lengths" that is hardcoded in the UI instead of the value stored in the defaults file
2) When we reverting defaults to initially solve this problem, it looks like it lost one of the '80' values from the old default (tes_lengths = [ [ 0, 90, 100, 120, 0, 30, 90, 80, 80, 120, 80 ] ]), so the new value is wrong and only contains 10 values instead of 11

**Comment by sjanzou** [comment] 2021-02-03 12:45
Confirmed @tyneises comment below with project file and latest patch build:

Update:
I think what was happening is that I was loading an older file that was overwriting the defaults with older defaults (that didn’t work). At the same time, the current defaults are off by 1 value, which caused the default configuration to crash for a different reason.
This approach of passing through hardcoded values through the UI seems over complicated and prone to version update errors. It seems simpler to:

1. make ‘tes_lengths’ (and any other hardcoded piping dimension inputs) an optional input in the compute module input table
2. check in the compute module if the input is defined and has the required dimensions
3. set to a default hardcoded somewhere in SSC/TCS if the input value is not defined

**Comment by sjanzou** [comment] 2021-02-03 12:52
@tyneises, @Matthew-Boyd I confirmed the issue with the project file from Ty and updated to project file to have the correct tes_lengths using the input browser per the Work document 
[GitHubIssuesSAM_419.docx](https://github.com/NREL/SAM/files/5918497/GitHubIssuesSAM_419.docx)

The default value has been updated in the SAM_419 branch off of patch, so new files will not have that issue.

Going forward, I would follow @tyneises advice to remove variables that have no corresponding UI widget to be optional values that are set in the compute modules. If you really want to keep them in the UI forms as hidden variables, then you can have them updated to the correct values listing the variable as "Calculated" and setting the desired value in an equation... Warning, this solution will wreak havoc in pySAM...

**Comment by tyneises** [comment] 2021-02-03 17:47
Thanks, @sjanzou.

The remaining issue is that the 2020.02.29 release default for 'tes_lengths' will crash a file originally saved in that version and then upgraded to 2020.11.29 and modified for serial tes operation.

@Matthew-Boyd can you please move the hardcoded piping values from the Physical Trough Thermal Storage ui page to the compute module?

**Comment by sjanzou** [comment] 2021-02-04 12:05
In SAM branch SAM_419 and pull request #525, the tes_lengths has been upgraded from previous versions as follows:
![image](https://user-images.githubusercontent.com/6498311/106890345-6df04800-66a6-11eb-9aa7-3d8b6f450694.png)

@tyneises, @Matthew-Boyd  After the hard code piping values are moved, that should close this issue.

**Comment by sjanzou** [comment] 2021-02-05 08:17
Closed with pull request 525 and 527

**Closed by sjanzou** 2021-02-05 08:17 UTC
Labels: bug
