### ISSUE TITLE
Hard crash during weather file download in upgrade script

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#518] opened 2021-01-29 18:43 UTC
**Describe the bug**
When opening older SAM files, a dialog box opens to allow downloading the older weather file if it is not available. When attempting to use this dialog, SAM crashes.

**To Reproduce**
1. Open https://github.com/NREL/SAM-documentation/blob/master/Unit%20Testing/Utility%20Rates/SAM%202017.1.17%20with%20TOU%20rates/APS%20TOU_battery_NREL.sam with SAM 2020.11.29
2. Choose yes on this dialog:
![image](https://user-images.githubusercontent.com/5530592/106314382-e7131980-6226-11eb-8014-5230be76770d.png)
(you may need to delete that file from your downloaded weather files)
3. SAM does a hard crash

**Expected behavior**
SAM shouldn't crash.

**Operating System and Version**
 - OS: Windows
 - Version 2020.11.29 R0

**Additional context**
It may be that the issue is I'm trying to jump too many versions. Additional testing may be needed to narrow down the issue. I haven't taken the time to gather messages through SAM debug yet.

**Comment by cpaulgilman** [comment] 2021-01-29 20:04
The upgrade script is using out-of-date URLs to access the NSRDB API in the function for SAM 2018.11.11.

This function was important for the SAM 2018.11.11 release when we removed the built-in collection of TMY3 and other weather files and replaced it with a more robust weather file download tools on the Solar Resource page to encourage users to use the latest NSRDB data instead of the out-of-date files that came with SAM. The upgrade script function was designed to help users navigate the change.

My recommendation would be to remove the code causing the crash and replace it with code to show a message that says something like:

> The weather file xxxxx.xxx is not in the solar resource library. 
> Setting the weather file to the first file in your solar resource library.
> Use the tools on the Solar Resource page to download or choose a different weather file.

@janinefreeman, @n8blair, @sjanzou: Any objections to this solution?

**Comment by sjanzou** [comment] 2021-01-29 21:04
Paul,

Sounds reasonable to me!

Thanks for finding this issue!
Steve

**Comment by janinefreeman** [comment] 2021-01-29 21:06
No objections here!

**Comment by cpaulgilman** [comment] 2021-02-04 22:40
It turns out the upgrade script handles the broken NSRDB URL gracefully:

![image](https://user-images.githubusercontent.com/27711933/106944363-567f8200-66db-11eb-8aa1-8bc0ee0f978b.png)

There are a few issues here:

* Upgrade script 2020.2.29 function changes Flat Plate PV and PVWatts configs to PV Battery and PVWatts battery when battery enabled before older functions run, so these older functions do not perform changes required for battery configurations.

* As noted above, the 2018.8.29 function had complicated checks and automatic setting of inputs for the solar resource page that were useful for the 2018.11.11 release but may not continue to work as the NSRDB API and SAM UI changes going forward.

* SAM 2017.1.17 does not seem to work properly on my Windows 10 machine (dropdown boxes don't work, Save As doesn't work), so I did my testing for this using SAM 2017.9.5 r4.

This issues should be fixed in 821c3324eb0a01ac2bb8da94328554e3e52aa7de.

**Comment by sjanzou** [comment] 2021-02-05 08:49
@cpaulgilman  Is this closed with PR #526?

**Closed** 2021-02-17 17:48 UTC
Labels: bug
