### ISSUE TITLE
Curtailed energy appears in cash flow when it shouldn't.

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#286] opened 2020-04-17 18:14 UTC
For this this PV-battery / Single Owner scenario with 5-minute simulations, https://github.com/NREL/SAM/files/4494590/curtailed_energy_bug.zip, curtailed energy appears in the cash flow:

![image](https://user-images.githubusercontent.com/27711933/79600272-bb5de300-809b-11ea-86b7-680cfea866bd.png)

But, in the time series results, system power generated is the same as system power generated before curtailment:

![image](https://user-images.githubusercontent.com/27711933/79600485-1263b800-809c-11ea-8aad-9be5d3bc144c.png)

For hourly simulations, the curtailed energy only appears in Year 1 of the cash flow:

![image](https://user-images.githubusercontent.com/27711933/79600556-2f988680-809c-11ea-8b62-b38cb792f059.png)

**Comment by sjanzou** [comment] 2020-04-29 11:19
The issue is addressed in the SAM_286 branch of ssc. However, there needs to be a clear definition of what curtailment energy is for battery front of meter calculations. Currently pv batt FOM gen subtracts "Electricity to battery from grid" from system production to get the "gen" value used through the grid compute module. Then, the hourly_energy_calculation class for the financial models adds "Electricity to battery from grid" back to the energy value used for revenue calculations.
![image](https://user-images.githubusercontent.com/6498311/80590389-04396400-89d9-11ea-98e5-4133c54fcfb8.png)

**Comment by sjanzou** [comment] 2020-04-29 11:25
The SAM_286 branch of ssc has been merged into patch and develop to address this issue but subject to review and reopening....
For the project file specified in this issue, the 5 minute case cash flow is now:
![image](https://user-images.githubusercontent.com/6498311/80590701-9ccfe400-89d9-11ea-8da4-5150fd7f6dbf.png)

and the hourly results are:
![image](https://user-images.githubusercontent.com/6498311/80590758-b2450e00-89d9-11ea-9e00-d671502439f8.png)

where the year 1 increase in energy produced includes the battery energy purchased from the grid. In this case, there is no electricity rate specified, so, the battery energy from the grid is free!

**Comment by cpaulgilman** [comment] 2020-05-01 18:23
This fix resolves the issue when there is no curtailment. But, for this PV case with 5-min simulations, curtailed energy and revenue does not seem to be calculated correctly. 

[curtailed-energy-hourly-vs-subhourly-bug.zip](https://github.com/NREL/SAM/files/4565785/curtailed-energy-hourly-vs-subhourly-bug.zip)

The curtailment input array curtails generation in the first 24 hours to 12 MW, which is visible in the time series results:

![image](https://user-images.githubusercontent.com/27711933/80829981-00563f00-8b9d-11ea-9b5d-179981b44aff.png)

Those hours of curtailment add up to 135282.2 kWh as calculated in the attached CSV file. However SAM reports zero curtailment kWh and $ revenue:

![image](https://user-images.githubusercontent.com/27711933/80830121-47443480-8b9d-11ea-8029-b3f30dde43b1.png)

The hourly case is similar, but does report curtailed kWh and revenue:

![image](https://user-images.githubusercontent.com/27711933/80830195-6ba01100-8b9d-11ea-92eb-1ad66a212f3a.png)

![image](https://user-images.githubusercontent.com/27711933/80830267-84102b80-8b9d-11ea-95ef-b80a27d51fc3.png)

**Comment by sjanzou** [comment] 2020-05-12 09:37
Fix with ssc branch SAM_286_2 and merge into patch and develop.
Issue was power to energy calculation and integer rather than double division.
![image](https://user-images.githubusercontent.com/6498311/81668175-82e2c800-9401-11ea-91c7-098f9e536c3b.png)

Test and update spreadsheet for all of day 1 power and energy calculations and compare with cashflow
![image](https://user-images.githubusercontent.com/6498311/81668241-9ee66980-9401-11ea-847e-1c824fabc74b.png)

And corresponding data table output for 5-minute case
![image](https://user-images.githubusercontent.com/6498311/81668425-e79e2280-9401-11ea-84f3-7ee04ca8ad7d.png)

**Closed by sjanzou** 2020-05-12 09:37 UTC
