### ISSUE TITLE
Restore PV priority option for battery dispatch

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#658] opened 2021-07-16 15:30 UTC
SAM 2017.9.5 has an option `batt_pv_choice` to set the priority for PV power for manual dispatch that is not available in later versions of SAM:

![image](https://user-images.githubusercontent.com/27711933/125971637-cccb66db-a9ad-4739-adb0-3b597dc46c6f.png)

To address user requests like https://sam.nrel.gov/forum/forum-general/3492 and to match REopt output for PV-only charging, we should consider restoring this feature. (Discharge to grid for BTM #338 is higher priority.)

The source code for 2017.1.17 (pre-GitHub) includes the following:

![image](https://user-images.githubusercontent.com/27711933/125971732-efdd29f5-48a3-43d4-8d26-1ef6927fbb64.png)

Tracing through the myriad of name changes through the arguments to each of the dispatch algorithms, shows: 
`batt_pv_choice (int)  -> (bool) pv_dispatch` as argument to `manual_dispatch_t` then to `int` in `dispatch_t` based class assigned to private class member `(int) _pv_dispatch_to_battery_first` with usage:

![image](https://user-images.githubusercontent.com/27711933/125971755-4ce2e965-d62b-4eec-9130-d249c2a3dab1.png)

and usage:
 
![image](https://user-images.githubusercontent.com/27711933/125971850-70d023b8-2279-48e4-be1c-ebe9b35a838b.png)

**Comment by brtietz** [comment] 2021-08-13 20:18
Throwing this on the release pile based on conversations with DOE and the need to match REopt's optimal dispatch.

**Comment by brtietz** [comment] 2021-09-08 15:22
Resolved in https://github.com/NREL/SAM/pull/692 and the associated SSC pull request. Closing.

**Comment by brtietz** [comment] 2022-06-09 19:38
Pull request #692 was necessary to get this working, but not sufficient. Users are requesting the ability to specify PV priority for battery charging for dispatch options other than custom, see https://sam.nrel.gov/forum/forum-general/3909 and https://sam.nrel.gov/component/kunena/forum-general/3492

**Comment by brtietz** [comment] 2022-10-23 21:09
The powerflow code looks relatively well set up to handle this if "Charge from system only when system output exceeds load" is unchecked. The issue is that the _dispatch_ code needs to set the battery power target to charge at the PV output until the battery is at max SOC. Going through the dispatch options:

- Price signals should be meeting the user's requests about charging during time of use rates automatically
- Peak shaving (and input grid power targets) should be meeting the grid power target, again making tradeoffs between charging and meeting load
- A user can already specify this with custom dispatch

Therefore the only dispatch method that needs to be modified is manual dispatch.

**Comment by brtietz** [comment] 2022-10-25 17:26
Closed in ssc 900 and #1205

**Closed by brtietz** 2022-10-25 17:26 UTC
Labels: requires help revision
