### ISSUE TITLE
Fix hard crashes Report Generator

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#385] opened 2020-09-24 22:01 UTC
@mjprilliman

**Comment by mjprilliman** [comment] 2020-10-23 19:16
Haven't spent too much time on this but the main thing is to take some function out of the function reference as trying to call them causes SAM to crash. I'll try to keep a running list of functions here:

sector()

**Comment by sjanzou** [comment] 2020-10-23 22:37
@mjprilliman, are the steps to reproduce:
1. Open report template
2. Open object editor
3. Add sector call
CRASH

**Comment by mjprilliman** [comment] 2020-10-23 22:43
@sjanzou Yes that about covers it. Everything seems to be fine until you close the sector call (closing parentheses) and then some process tries to run it. At that point SAM freezes then hard crashes.

**Comment by sjanzou** [comment] 2020-11-18 11:41
See Pull Request #442 and attached document for fixes. 
Note that the report editor supports only the pdf device context and can draw on, place images, and render tables. There is currently no direct support for the plPlotCtrl on any widget on the report editor and the crash was caused by non-implemented functions being called in the script window or the report editor.
[SAM_385.docx](https://github.com/NREL/SAM/files/5559734/SAM_385.docx)

**Closed** 2020-11-19 04:09 UTC
