### ISSUE TITLE
Allow time-series input of electricity rates

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#118] opened 2018-11-01 21:05 UTC
To facilitate modeling of real-time prices, it would be useful to be able to enter an 8760 (or potentially a sub-hourly) price signal ($/kWh).

**Comment by cpaulgilman** [comment] 2019-05-23 23:09
This is a duplicate of https://github.com/NREL/SAM/issues/78.

**Closed by cpaulgilman** 2019-05-23 23:09 UTC
Labels: utility rate enhancement
