### ISSUE TITLE
O&M Bug in Standalone Battery

### ISSUE THREAD

**Issue by dguittet** [NREL/SAM#901] opened 2022-01-26 00:07 UTC
### Describe the bug

The O&M costs in the cashflow do not add up because the `cf_om_capacity1_expense` should replace `cf_om_capacity_expense` in the line item for O&M capacity-based expense.

### To Reproduce

Open a Standalone Battery Single Owner configuration and click Simulate.

### Screenshots

![image](https://user-images.githubusercontent.com/29387736/151070297-c842025c-298b-4743-b739-2ef0fe21fb34.png)

### Operating System and Version

 - OS: [macOS]
 - Version [SAM 2021.12.2]

**Comment by cpaulgilman** [comment] 2022-01-26 22:34
This is related to or a duplicate of https://github.com/NREL/SAM/issues/901

**Closed** 2022-02-11 19:35 UTC
Labels: bug
