### ISSUE TITLE
PV 3D Shade Calculator returns time zone of zero

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#207] opened 2019-06-25 22:39 UTC
1. For a Detailed Photovoltaic case, go to Shading and Losses.

2. Click **Open 3D shade calculator**.

3. On Location tab, type an address and click **Lookup address**.

Latitude and longitude are correct, but time zone is zero.

**Comment by sjanzou** [comment] 2019-12-10 11:53
The issue is that the Mapquest API used for geocoding does not return a timezone value. The team at developer.nrel.gov has been contacted for an alternative.

**Comment by sjanzou** [comment] 2019-12-10 14:01
Fixed with BING API using wex commit 829b2bc0dcd236900e5ea55b920d6b3febfef3c2

**Closed by sjanzou** 2019-12-10 14:01 UTC
Labels: bug
