### ISSUE TITLE
Update battery controller to consider grid interconnection limit

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#181] opened 2019-05-16 17:23 UTC
With the addition of a grid interconnection limit, it will be nice to have the battery controller consider this limit when dispatching.

**Comment by cpaulgilman** [comment] 2019-05-28 21:39
Export limiting is a common request by PV modelers, for a description see:

https://www.solaranalytics.com/us/blog/what-is-solar-export-limiting-and-how-to-find-your-lost-energy. 

And this SMA article about the export limiting feature on some inverters:

https://www.sma-uk.com/solar-systems/export-limitation.html

Users want to know how much energy they lose over the year due to this limiting.

**Comment by janinefreeman** [comment] 2020-06-05 20:53
@sjanzou @dguittet  Is this complete, or still on our to-do list?

**Comment by dguittet** [comment] 2020-06-05 20:54
This is not complete. The grid interconnection limit is applied after dispatch and not factored into the dispatch decision.

**Comment by cpaulgilman** [comment] 2020-09-21 21:04
For battery configurations with Merchant Plant, cleared capacity requirements for both energy market and ancillary services should be considered by the automated dispatch options.

**Comment by dguittet** [comment] 2020-11-11 17:37
I'm going to move this out of the upcoming release since I think it needs to be done in conjunction with the other grid requirements, and be part of a larger merchant plant dispatch optimization framework.

**Comment by brtietz** [comment] 2021-08-19 16:00
While working on https://github.com/NREL/SAM/issues/658 I wrote a powerflow test that tried to push a DC battery into grid export. The result was the powerflow calculations listed grid_to_load as a negative number. It's not surprising that the powerflow calcs would need work at that level, but wanted to record the specifics here for planning purposes.

**Comment by cpaulgilman** [comment] 2022-11-03 23:18
@milindsmart Good point. I added a note to the Help topic for the Grid Limits page to explain that battery dispatch does not consider the grid interconnection limit (but does consider grid outages). This will be available in the Fall 2022 Release of SAM.

**Comment by cpaulgilman** [comment] 2023-09-15 21:00
https://sam.nrel.gov/forum/forum-general/4366

**Comment by brtietz** [comment] 2023-12-13 22:55
This seems like it will be increasingly important for hybrids, so hoping to sneak it into the 2024 release.

**Comment by andreaswabbes** [comment] 2024-07-09 09:06
I can confirm that this is a very urgent topic. An option 'charge from curtailed energy' (similar to clipped energy for DC coupled) would be brilliant. Many sites are over-dimensioned on the PV side and are looking towards batteries to avoid waiting for an expansion of grid connection.

**Closed** 2024-10-31 14:37 UTC
Labels: new feature, battery, hybrid
