### ISSUE TITLE
Plot font hard to read with wxWidgets update

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#883] opened 2022-01-12 16:46 UTC
### Describe the bug

The font used in the plot widgets is harder to read after the update to wxWidgets 3.1.5

### Screenshots

![image](https://user-images.githubusercontent.com/54449384/149183969-92c2b8f9-e17e-4ad6-bbc3-fb0aa0ce56f7.png)

### Operating System and Version

 - OS: [Windows]
 - Version [e.g. SAM 2021.12.02 r0]

**Comment by sjanzou** [comment] 2022-01-15 11:59
@mjprilliman, please review https://github.com/NREL/wex/pull/135 and let me know if that fixes the issue on your machine. I tested on several external monitors and a laptop screen and the renderer used in the wex SAM_883 branch was the sharpest. Thanks!

**Comment by sjanzou** [comment] 2022-01-17 09:13
The issue is not yet resolved - wex sandbox using wx3.1.1 on left (clearer text) vs wx3.1.5 on right with exact same wex sandbox tests
![image](https://user-images.githubusercontent.com/6498311/149741007-e3cb4bc9-6d83-427b-b9ed-1360d4a9ac7e.png)

**Comment by sjanzou** [comment] 2022-01-17 13:00
Latest wex updates matching closely with previous release
![image](https://user-images.githubusercontent.com/6498311/149773683-0a1534d4-91fd-4fcf-ab8d-1bd9d1afcf5f.png)

**Comment by sjanzou** [comment] 2022-01-22 12:10
Fixed with https://github.com/NREL/wex/pull/135 (into patch) and https://github.com/NREL/wex/pull/136 (patch into develop)

**Closed by sjanzou** 2022-01-22 12:10 UTC
Labels: bug
